<a href="https://colab.research.google.com/github/Bavesh-08/fake-news-classifier-using-Bi-directional-LSTM/blob/main/fake_news_predction_using_Bidirectional_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df=pd.read_csv('/content/FakeNewsNet.csv')
df.head()

,title,news_url,source_domain,tweet_num,real
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42,1
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0,1
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63,1
3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20,1
4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38,1

In [ ]:
###Drop Nan Values
df=df.dropna()

In [ ]:
## Get the Independent Features

X=df.drop('real',axis=1)

## Get the Dependent features
y=df['real']

In [ ]:
y.value_counts()

real
1    17441
0     5755
Name: count, dtype: int64

In [ ]:
X.shape,y.shape

((23196, 4), (23196,))

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [ ]:
### Vocabulary size
voc_size=10000

In [ ]:
# inehot encoding

messages=X.copy()
messages['title'][1]

"People's Choice Awards 2018: The best red carpet looks"

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
18196
18197
18198
18199
18200
18201
18202
18203
18204
18205
18206
18207
18208
18209
18210
18211
18212
18213
18214
18215
18216
18217
18218
18219
18220
18221
18222
18223
18224
18225
18226
18227
18228
18229
18230
18231
18232
18233
18234
18235
18236
18237
18238
18239
18240
18241
18242
18243
18244
18245
18246
18247
18248
18249
18250
18251
18252
18253
18254
18255
18256
18257
18258
18259
18260
18261
18262
18263
18264
18265
18266
18267
18268
18269
18270
18271
18272
18273
18274
18275
18276
18277
18278
18279
18280
18281
18282
18283
18284
18285
18286
18287
18288
18289
18290
18291
18292
18293
18294
18295
18296
18297
18298
18299
18300
18301
18302
18303
18304
18305
18306
18307
18308
18309
18310
18311
18312
18313
18314
18315
18316
18317
18318
18319
18320
18321
18322
18323
18324
18325
18326
18327
18328
18329
18330
18331
18332
18333
18334
18335
18336
18337
18338
18339
18340
18341
18342
18343
18344
18345
18346
18347
18348
18349
18350
18351
18352
18353
18354
18355
18356
18357
18358
18359
18360
18361
18362
18363
18364
18365
18366
18367
18368
18369
18370
18371
18372
18373
18374
18375
18376
18377
18378
18379
18380
18381
18382
18383
18384
18385
18386
18387
18388
18389
18390
18391
18392
18393
18394
18395
18396
18397
18398
18399
18400
18401
18402
18403
18404
18405
18406
18407
18408
18409
18410
18411
18412
18413
18414
18415
18416
18417
18418
18419
18420
18421
18422
18423
18424
18425
18426
18427
18428
18429
18430
18431
18432
18433
18434
18435
18436
18437
18438
18439
18440
18441
18442
18443
18444
18445
18446
18447
18448
18449
18450
18451
18452
18453
18454
18455
18456
18457
18458
18459
18460
18461
18462
18463
18464
18465
18466
18467
18468
18469
18470
18471
18472
18473
18474
18475
18476
18477
18478
18479
18480
18481
18482
18483
18484
18485
18486
18487
18488
18489
18490
18491
18492
18493
18494
18495
18496
18497
18498
18499
18500
18501
18502
18503
18504
18505
18506
18507
18508
18509
18510
18511
18512
18513
18514
18515
18516
18517
18518
18519
18520
18521
18522
18523
18524
18525
18526
18527
18528
18529
18530
18531
18532
18533
18534
18535
18536
18537
18538
18539
18540
18541
18542
18543
18544
18545
18546
18547
18548
18549
18550
18551
18552
18553
18554
18555
18556
18557
18558
18559
18560
18561
18562
18563
18564
18565
18566
18567
18568
18569
18570
18571
18572
18573
18574
18575
18576
18577
18578
18579
18580
18581
18582
18583
18584
18585
18586
18587
18588
18589
18590
18591
18592
18593
18594
18595
18596
18597
18598
18599
18600
18601
18602
18603
18604
18605
18606
18607
18608
18609
18610
18611
18612
18613
18614
18615
18616
18617
18618
18619
18620
18621
18622
18623
18624
18625
18626
18627
18628
18629
18630
18631
18632
18633
18634
18635
18636
18637
18638
18639
18640
18641
18642
18643
18644
18645
18646
18647
18648
18649
18650
18651
18652
18653
18654
18655
18656
18657
18658
18659
18660
18661
18662
18663
18664
18665
18666
18667
18668
18669
18670
18671
18672
18673
18674
18675
18676
18677
18678
18679
18680
18681
18682
18683
18684
18685
18686
18687
18688
18689
18690
18691
18692
18693
18694
18695
18696
18697
18698
18699
18700
18701
18702
18703
18704
18705
18706
18707
18708
18709
18710
18711
18712
18713
18714
18715
18716
18717
18718
18719
18720
18721
18722
18723
18724
18725
18726
18727
18728
18729
18730
18731
18732
18733
18734
18735
18736
18737
18738
18739
18740
18741
18742
18743
18744
18745
18746
18747
18748
18749
18750
18751
18752
18753
18754
18755
18756
18757
18758
18759
18760
18761
18762
18763
18764
18765
18766
18767
18768
18769
18770
18771
18772
18773
18774
18775
18776
18777
18778
18779
18780
18781
18782
18783
18784
18785
18786
18787
18788
18789
18790
18791
18792
18793
18794
18795
18796
18797
18798
18799
18800
18801
18802
18803
18804
18805
18806
18807
18808
18809
18810
18811
18812
18813
18814
18815
18816
18817
18818
18819
18820
18821
18822
18823
18824
18825
18826
18827
18828
18829
18830
18831
18832
18833
18834
18835
18836
18837
18838
18839
18840
18841
18842
18843
18844
18845
18846
18847
18848
18849
18850
18851
18852
18853
18854
18855
18856
18857
18858
18859
18860
18861
18862
18863
18864
18865
18866
18867
18868
18869
18870
18871
18872
18873
18874
18875
18876
18877
18878
18879
18880
18881
18882
18883
18884
18885
18886
18887
18888
18889
18890
18891
18892
18893
18894
18895
18896
18897
18898
18899
18900
18901
18902
18903
18904
18905
18906
18907
18908
18909
18910
18911
18912
18913
18914
18915
18916
18917
18918
18919
18920
18921
18922
18923
18924
18925
18926
18927
18928
18929
18930
18931
18932
18933
18934
18935
18936
18937
18938
18939
18940
18941
18942
18943
18944
18945
18946
18947
18948
18949
18950
18951
18952
18953
18954
18955
18956
18957
18958
18959
18960
18961
18962
18963
18964
18965
18966
18967
18968
18969
18970
18971
18972
18973
18974
18975
18976
18977
18978
18979
18980
18981
18982
18983
18984
18985
18986
18987
18988
18989
18990
18991
18992
18993
18994
18995
18996
18997
18998
18999
19000
19001
19002
19003
19004
19005
19006
19007
19008
19009
19010
19011
19012
19013
19014
19015
19016
19017
19018
19019
19020
19021
19022
19023
19024
19025
19026
19027
19028
19029
19030
19031
19032
19033
19034
19035
19036
19037
19038
19039
19040
19041
19042
19043
19044
19045
19046
19047
19048
19049
19050
19051
19052
19053
19054
19055
19056
19057
19058
19059
19060
19061
19062
19063
19064
19065
19066
19067
19068
19069
19070
19071
19072
19073
19074
19075
19076
19077
19078
19079
19080
19081
19082
19083
19084
19085
19086
19087
19088
19089
19090
19091
19092
19093
19094
19095
19096
19097
19098
19099
19100
19101
19102
19103
19104
19105
19106
19107
19108
19109
19110
19111
19112
19113
19114
19115
19116
19117
19118
19119
19120
19121
19122
19123
19124
19125
19126
19127
19128
19129
19130
19131
19132
19133
19134
19135
19136
19137
19138
19139
19140
19141
19142
19143
19144
19145
19146
19147
19148
19149
19150
19151
19152
19153
19154
19155
19156
19157
19158
19159
19160
19161
19162
19163
19164
19165
19166
19167
19168
19169
19170
19171
19172
19173
19174
19175
19176
19177
19178
19179
19180
19181
19182
19183
19184
19185
19186
19187
19188
19189
19190
19191
19192
19193
19194
19195
19196
19197
19198
19199
19200
19201
19202
19203
19204
19205
19206
19207
19208
19209
19210
19211
19212
19213
19214
19215
19216
19217
19218
19219
19220
19221
19222
19223
19224
19225
19226
19227
19228
19229
19230
19231
19232
19233
19234
19235
19236
19237
19238
19239
19240
19241
19242
19243
19244
19245
19246
19247
19248
19249
19250
19251
19252
19253
19254
19255
19256
19257
19258
19259
19260
19261
19262
19263
19264
19265
19266
19267
19268
19269
19270
19271
19272
19273
19274
19275
19276
19277
19278
19279
19280
19281
19282
19283
19284
19285
19286
19287
19288
19289
19290
19291
19292
19293
19294
19295
19296
19297
19298
19299
19300
19301
19302
19303
19304
19305
19306
19307
19308
19309
19310
19311
19312
19313
19314
19315
19316
19317
19318
19319
19320
19321
19322
19323
19324
19325
19326
19327
19328
19329
19330
19331
19332
19333
19334
19335
19336
19337
19338
19339
19340
19341
19342
19343
19344
19345
19346
19347
19348
19349
19350
19351
19352
19353
19354
19355
19356
19357
19358
19359
19360
19361
19362
19363
19364
19365
19366
19367
19368
19369
19370
19371
19372
19373
19374
19375
19376
19377
19378
19379
19380
19381
19382
19383
19384
19385
19386
19387
19388
19389
19390
19391
19392
19393
19394
19395
19396
19397
19398
19399
19400
19401
19402
19403
19404
19405
19406
19407
19408
19409
19410
19411
19412
19413
19414
19415
19416
19417
19418
19419
19420
19421
19422
19423
19424
19425
19426
19427
19428
19429
19430
19431
19432
19433
19434
19435
19436
19437
19438
19439
19440
19441
19442
19443
19444
19445
19446
19447
19448
19449
19450
19451
19452
19453
19454
19455
19456
19457
19458
19459
19460
19461
19462
19463
19464
19465
19466
19467
19468
19469
19470
19471
19472
19473
19474
19475
19476
19477
19478
19479
19480
19481
19482
19483
19484
19485
19486
19487
19488
19489
19490
19491
19492
19493
19494
19495
19496
19497
19498
19499
19500
19501
19502
19503
19504
19505
19506
19507
19508
19509
19510
19511
19512
19513
19514
19515
19516
19517
19518
19519
19520
19521
19522
19523
19524
19525
19526
19527
19528
19529
19530
19531
19532
19533
19534
19535
19536
19537
19538
19539
19540
19541
19542
19543
19544
19545
19546
19547
19548
19549
19550
19551
19552
19553
19554
19555
19556
19557
19558
19559
19560
19561
19562
19563
19564
19565
19566
19567
19568
19569
19570
19571
19572
19573
19574
19575
19576
19577
19578
19579
19580
19581
19582
19583
19584
19585
19586
19587
19588
19589
19590
19591
19592
19593
19594
19595
19596
19597
19598
19599
19600
19601
19602
19603
19604
19605
19606
19607
19608
19609
19610
19611
19612
19613
19614
19615
19616
19617
19618
19619
19620
19621
19622
19623
19624
19625
19626
19627
19628
19629
19630
19631
19632
19633
19634
19635
19636
19637
19638
19639
19640
19641
19642
19643
19644
19645
19646
19647
19648
19649
19650
19651
19652
19653
19654
19655
19656
19657
19658
19659
19660
19661
19662
19663
19664
19665
19666
19667
19668
19669
19670
19671
19672
19673
19674
19675
19676
19677
19678
19679
19680
19681
19682
19683
19684
19685
19686
19687
19688
19689
19690
19691
19692
19693
19694
19695
19696
19697
19698
19699
19700
19701
19702
19703
19704
19705
19706
19707
19708
19709
19710
19711
19712
19713
19714
19715
19716
19717
19718
19719
19720
19721
19722
19723
19724
19725
19726
19727
19728
19729
19730
19731
19732
19733
19734
19735
19736
19737
19738
19739
19740
19741
19742
19743
19744
19745
19746
19747
19748
19749
19750
19751
19752
19753
19754
19755
19756
19757
19758
19759
19760
19761
19762
19763
19764
19765
19766
19767
19768
19769
19770
19771
19772
19773
19774
19775
19776
19777
19778
19779
19780
19781
19782
19783
19784
19785
19786
19787
19788
19789
19790
19791
19792
19793
19794
19795
19796
19797
19798
19799
19800
19801
19802
19803
19804
19805
19806
19807
19808
19809
19810
19811
19812
19813
19814
19815
19816
19817
19818
19819
19820
19821
19822
19823
19824
19825
19826
19827
19828
19829
19830
19831
19832
19833
19834
19835
19836
19837
19838
19839
19840
19841
19842
19843
19844
19845
19846
19847
19848
19849
19850
19851
19852
19853
19854
19855
19856
19857
19858
19859
19860
19861
19862
19863
19864
19865
19866
19867
19868
19869
19870
19871
19872
19873
19874
19875
19876
19877
19878
19879
19880
19881
19882
19883
19884
19885
19886
19887
19888
19889
19890
19891
19892
19893
19894
19895
19896
19897
19898
19899
19900
19901
19902
19903
19904
19905
19906
19907
19908
19909
19910
19911
19912
19913
19914
19915
19916
19917
19918
19919
19920
19921
19922
19923
19924
19925
19926
19927
19928
19929
19930
19931
19932
19933
19934
19935
19936
19937
19938
19939
19940
19941
19942
19943
19944
19945
19946
19947
19948
19949
19950
19951
19952
19953
19954
19955
19956
19957
19958
19959
19960
19961
19962
19963
19964
19965
19966
19967
19968
19969
19970
19971
19972
19973
19974
19975
19976
19977
19978
19979
19980
19981
19982
19983
19984
19985
19986
19987
19988
19989
19990
19991
19992
19993
19994
19995
19996
19997
19998
19999
20000
20001
20002
20003
20004
20005
20006
20007
20008
20009
20010
20011
20012
20013
20014
20015
20016
20017
20018
20019
20020
20021
20022
20023
20024
20025
20026
20027
20028
20029
20030
20031
20032
20033
20034
20035
20036
20037
20038
20039
20040
20041
20042
20043
20044
20045
20046
20047
20048
20049
20050
20051
20052
20053
20054
20055
20056
20057
20058
20059
20060
20061
20062
20063
20064
20065
20066
20067
20068
20069
20070
20071
20072
20073
20074
20075
20076
20077
20078
20079
20080
20081
20082
20083
20084
20085
20086
20087
20088
20089
20090
20091
20092
20093
20094
20095
20096
20097
20098
20099
20100
20101
20102
20103
20104
20105
20106
20107
20108
20109
20110
20111
20112
20113
20114
20115
20116
20117
20118
20119
20120
20121
20122
20123
20124
20125
20126
20127
20128
20129
20130
20131
20132
20133
20134
20135
20136
20137
20138
20139
20140
20141
20142
20143
20144
20145
20146
20147
20148
20149
20150
20151
20152
20153
20154
20155
20156
20157
20158
20159
20160
20161
20162
20163
20164
20165
20166
20167
20168
20169
20170
20171
20172
20173
20174
20175
20176
20177
20178
20179
20180
20181
20182
20183
20184
20185
20186
20187
20188
20189
20190
20191
20192
20193
20194
20195
20196
20197
20198
20199
20200
20201
20202
20203
20204
20205
20206
20207
20208
20209
20210
20211
20212
20213
20214
20215
20216
20217
20218
20219
20220
20221
20222
20223
20224
20225
20226
20227
20228
20229
20230
20231
20232
20233
20234
20235
20236
20237
20238
20239
20240
20241
20242
20243
20244
20245
20246
20247
20248
20249
20250
20251
20252
20253
20254
20255
20256
20257
20258
20259
20260
20261
20262
20263
20264
20265
20266
20267
20268
20269
20270
20271
20272
20273
20274
20275
20276
20277
20278
20279
20280
20281
20282
20283
20284
20285
20286
20287
20288
20289
20290
20291
20292
20293
20294
20295
20296
20297
20298
20299
20300
20301
20302
20303
20304
20305
20306
20307
20308
20309
20310
20311
20312
20313
20314
20315
20316
20317
20318
20319
20320
20321
20322
20323
20324
20325
20326
20327
20328
20329
20330
20331
20332
20333
20334
20335
20336
20337
20338
20339
20340
20341
20342
20343
20344
20345
20346
20347
20348
20349
20350
20351
20352
20353
20354
20355
20356
20357
20358
20359
20360
20361
20362
20363
20364
20365
20366
20367
20368
20369
20370
20371
20372
20373
20374
20375
20376
20377
20378
20379
20380
20381
20382
20383
20384
20385
20386
20387
20388
20389
20390
20391
20392
20393
20394
20395
20396
20397
20398
20399
20400
20401
20402
20403
20404
20405
20406
20407
20408
20409
20410
20411
20412
20413
20414
20415
20416
20417
20418
20419
20420
20421
20422
20423
20424
20425
20426
20427
20428
20429
20430
20431
20432
20433
20434
20435
20436
20437
20438
20439
20440
20441
20442
20443
20444
20445
20446
20447
20448
20449
20450
20451
20452
20453
20454
20455
20456
20457
20458
20459
20460
20461
20462
20463
20464
20465
20466
20467
20468
20469
20470
20471
20472
20473
20474
20475
20476
20477
20478
20479
20480
20481
20482
20483
20484
20485
20486
20487
20488
20489
20490
20491
20492
20493
20494
20495
20496
20497
20498
20499
20500
20501
20502
20503
20504
20505
20506
20507
20508
20509
20510
20511
20512
20513
20514
20515
20516
20517
20518
20519
20520
20521
20522
20523
20524
20525
20526
20527
20528
20529
20530
20531
20532
20533
20534
20535
20536
20537
20538
20539
20540
20541
20542
20543
20544
20545
20546
20547
20548
20549
20550
20551
20552
20553
20554
20555
20556
20557
20558
20559
20560
20561
20562
20563
20564
20565
20566
20567
20568
20569
20570
20571
20572
20573
20574
20575
20576
20577
20578
20579
20580
20581
20582
20583
20584
20585
20586
20587
20588
20589
20590
20591
20592
20593
20594
20595
20596
20597
20598
20599
20600
20601
20602
20603
20604
20605
20606
20607
20608
20609
20610
20611
20612
20613
20614
20615
20616
20617
20618
20619
20620
20621
20622
20623
20624
20625
20626
20627
20628
20629
20630
20631
20632
20633
20634
20635
20636
20637
20638
20639
20640
20641
20642
20643
20644
20645
20646
20647
20648
20649
20650
20651
20652
20653
20654
20655
20656
20657
20658
20659
20660
20661
20662
20663
20664
20665
20666
20667
20668
20669
20670
20671
20672
20673
20674
20675
20676
20677
20678
20679
20680
20681
20682
20683
20684
20685
20686
20687
20688
20689
20690
20691
20692
20693
20694
20695
20696
20697
20698
20699
20700
20701
20702
20703
20704
20705
20706
20707
20708
20709
20710
20711
20712
20713
20714
20715
20716
20717
20718
20719
20720
20721
20722
20723
20724
20725
20726
20727
20728
20729
20730
20731
20732
20733
20734
20735
20736
20737
20738
20739
20740
20741
20742
20743
20744
20745
20746
20747
20748
20749
20750
20751
20752
20753
20754
20755
20756
20757
20758
20759
20760
20761
20762
20763
20764
20765
20766
20767
20768
20769
20770
20771
20772
20773
20774
20775
20776
20777
20778
20779
20780
20781
20782
20783
20784
20785
20786
20787
20788
20789
20790
20791
20792
20793
20794
20795
20796
20797
20798
20799
20800
20801
20802
20803
20804
20805
20806
20807
20808
20809
20810
20811
20812
20813
20814
20815
20816
20817
20818
20819
20820
20821
20822
20823
20824
20825
20826
20827
20828
20829
20830
20831
20832
20833
20834
20835
20836
20837
20838
20839
20840
20841
20842
20843
20844
20845
20846
20847
20848
20849
20850
20851
20852
20853
20854
20855
20856
20857
20858
20859
20860
20861
20862
20863
20864
20865
20866
20867
20868
20869
20870
20871
20872
20873
20874
20875
20876
20877
20878
20879
20880
20881
20882
20883
20884
20885
20886
20887
20888
20889
20890
20891
20892
20893
20894
20895
20896
20897
20898
20899
20900
20901
20902
20903
20904
20905
20906
20907
20908
20909
20910
20911
20912
20913
20914
20915
20916
20917
20918
20919
20920
20921
20922
20923
20924
20925
20926
20927
20928
20929
20930
20931
20932
20933
20934
20935
20936
20937
20938
20939
20940
20941
20942
20943
20944
20945
20946
20947
20948
20949
20950
20951
20952
20953
20954
20955
20956
20957
20958
20959
20960
20961
20962
20963
20964
20965
20966
20967
20968
20969
20970
20971
20972
20973
20974
20975
20976
20977
20978
20979
20980
20981
20982
20983
20984
20985
20986
20987
20988
20989
20990
20991
20992
20993
20994
20995
20996
20997
20998
20999
21000
21001
21002
21003
21004
21005
21006
21007
21008
21009
21010
21011
21012
21013
21014
21015
21016
21017
21018
21019
21020
21021
21022
21023
21024
21025
21026
21027
21028
21029
21030
21031
21032
21033
21034
21035
21036
21037
21038
21039
21040
21041
21042
21043
21044
21045
21046
21047
21048
21049
21050
21051
21052
21053
21054
21055
21056
21057
21058
21059
21060
21061
21062
21063
21064
21065
21066
21067
21068
21069
21070
21071
21072
21073
21074
21075
21076
21077
21078
21079
21080
21081
21082
21083
21084
21085
21086
21087
21088
21089
21090
21091
21092
21093
21094
21095
21096
21097
21098
21099
21100
21101
21102
21103
21104
21105
21106
21107
21108
21109
21110
21111
21112
21113
21114
21115
21116
21117
21118
21119
21120
21121
21122
21123
21124
21125
21126
21127
21128
21129
21130
21131
21132
21133
21134
21135
21136
21137
21138
21139
21140
21141
21142
21143
21144
21145
21146
21147
21148
21149
21150
21151
21152
21153
21154
21155
21156
21157
21158
21159
21160
21161
21162
21163
21164
21165
21166
21167
21168
21169
21170
21171
21172
21173
21174
21175
21176
21177
21178
21179
21180
21181
21182
21183
21184
21185
21186
21187
21188
21189
21190
21191
21192
21193
21194
21195
21196
21197
21198
21199
21200
21201
21202
21203
21204
21205
21206
21207
21208
21209
21210
21211
21212
21213
21214
21215
21216
21217
21218
21219
21220
21221
21222
21223
21224
21225
21226
21227
21228
21229
21230
21231
21232
21233
21234
21235
21236
21237
21238
21239
21240
21241
21242
21243
21244
21245
21246
21247
21248
21249
21250
21251
21252
21253
21254
21255
21256
21257
21258
21259
21260
21261
21262
21263
21264
21265
21266
21267
21268
21269
21270
21271
21272
21273
21274
21275
21276
21277
21278
21279
21280
21281
21282
21283
21284
21285
21286
21287
21288
21289
21290
21291
21292
21293
21294
21295
21296
21297
21298
21299
21300
21301
21302
21303
21304
21305
21306
21307
21308
21309
21310
21311
21312
21313
21314
21315
21316
21317
21318
21319
21320
21321
21322
21323
21324
21325
21326
21327
21328
21329
21330
21331
21332
21333
21334
21335
21336
21337
21338
21339
21340
21341
21342
21343
21344
21345
21346
21347
21348
21349
21350
21351
21352
21353
21354
21355
21356
21357
21358
21359
21360
21361
21362
21363
21364
21365
21366
21367
21368
21369
21370
21371
21372
21373
21374
21375
21376
21377
21378
21379
21380
21381
21382
21383
21384
21385
21386
21387
21388
21389
21390
21391
21392
21393
21394
21395
21396
21397
21398
21399
21400
21401
21402
21403
21404
21405
21406
21407
21408
21409
21410
21411
21412
21413
21414
21415
21416
21417
21418
21419
21420
21421
21422
21423
21424
21425
21426
21427
21428
21429
21430
21431
21432
21433
21434
21435
21436
21437
21438
21439
21440
21441
21442
21443
21444
21445
21446
21447
21448
21449
21450
21451
21452
21453
21454
21455
21456
21457
21458
21459
21460
21461
21462
21463
21464
21465
21466
21467
21468
21469
21470
21471
21472
21473
21474
21475
21476
21477
21478
21479
21480
21481
21482
21483
21484
21485
21486
21487
21488
21489
21490
21491
21492
21493
21494
21495
21496
21497
21498
21499
21500
21501
21502
21503
21504
21505
21506
21507
21508
21509
21510
21511
21512
21513
21514
21515
21516
21517
21518
21519

In [ ]:
corpus

['kandi burruss explod rape accus real housew atlanta reunion video',
 'peopl choic award best red carpet look',
 'sophia bush send sweet birthday messag one tree hill co star hilari burton breyton eva',
 'colombian singer maluma spark rumour inappropri relationship aunt',
 'gossip girl year later upper east sider shock world chang pop cultur forev',
 'gwen stefani got dump blake shelton jealousi drama exclus',
 'broward counti sheriff fire lie parkland',
 'amber rose shut french montana date rumor call rapper bruvaaa',
 'mindi kale make first post babi appear disneyland wrinkl time co star',
 'katharin mcphee butcher toni nomin drink',
 'wag miami star ashley nicol robert philip wheeler marri',
 'mel gibson hollywood pedophil nowher left hide',
 'medium tyler henri address chill messag kristin cavallari deceas brother express read',
 'dwt season result week disney night',
 'via cq subscrib tax foundat',
 'reason tarek el moussa overcom latest back injuri',
 'david cassidi cut estrang daughter kati complet leav son beau',
 'actress brigitt nielsen given birth fifth child',
 'kardashian donat whop sum la vega mass shoot victim',
 'brad pitt open get back togeth angelina rumor',
 'pink announc tour drop new singl',
 'glimps relationship meghan markl kate middleton princ harri princ william british royal wed',
 'johnni depp charli sheen kevin dillon reunit',
 'kati holm jami foxx expect babi new report claim want start famili',
 'ryan phillipp show insan chisel bod shirtless snow',
 'pretti celebr book would look good coffe tabl',
 'pink panic hang l hotel ama perform',
 'ann hathaway preemptiv shut bodi shamer instagram post weight gain',
 'watch kendal jenner first ever adida ad',
 'bachelor alum vienna girardi reveal gender twin',
 'teen mom og tyler baltierra reveal lost lb',
 'kim kardashian west say kid know famou clue',
 'ladi crush angelina joli',
 'jennif lawrenc blast harvey weinstein legal tactic',
 'cw renew supernatur arrow supergirl riverdal',
 'harvey weinstein hire investig spi accus varieti',
 'mario lopez admit cheat ali landri day wed',
 'watch marri first sight jonathan squirm confront molli sister',
 'farewel midnight comedi central quiz show end realli suck',
 'list beyonc knowl date',
 'kati perri say readi soul overhaul kill ego past year',
 'rose lesli made kit harington wear jon snow costum',
 'kate middleton wear diana tiara queen diplomat recept',
 'michael fassbend alicia vikand split month date',
 'ryan locht clear fals report charg incid rio olymp',
 'bachelorett star chad johnson reveal sabotag relationship toll mom death took',
 'kourtney kardashian home swarm tarantula',
 'crib kim kardashian west beyonc use',
 'kim kardashian insist sick kany west go hospit saint pneumonia scare sourc',
 'audrina patridg divorc corey bohan seek joint custodi',
 'mama june trash talk daughter pumpkin fianc',
 'scott brought girl disick disrupt anoth trip kardashian famili reaction priceless watch',
 'rachel brosnahan attend toni award day aunt kate spade death',
 'norvel present danc star product line',
 'save bell mark paul gosselaar tiffani thiessen reunit',
 'sofia richi kourtney kardashian stay away scott disick',
 'would consid color lip balm makeup product',
 'rhomiami alum joanna krupa romain zago final divorc',
 'kate middleton realli want get pregnant babi princ william exclus',
 'kj apa roast cole sprous instagram throwback photo',
 'less bounc iggi azalea say lost lb week twerk latest music video',
 'insid matt lauer quiet life year today show fire well',
 'sean penn talk haiti humanitarian hollywood',
 'j balvin live moment dream girl new ahora video',
 'anthoni michael hall sentenc three year probat assault',
 'jada pinkett smith leav smith august alsina despit claim',
 'serena lose exhibit comeback give birth',
 'thoma rhett wife open turbul adopt process',
 'britney spear agre pay kevin federlin thousand child support report',
 'photo celebr wear jacket properli one know dress fall weather',
 'luke bryan joke gwen stefani hot blake shelton watch',
 'cardi b advic everyon wrap khlo kardashian relationship drama',
 'patient protect afford care act',
 'blake live condemn harvey weinstein amid alleg',
 'see hilari christma gift jennif lawrenc gave bff kri jenner',
 'investig celebr parent trend placenta pill bank cord blood babywear',
 'togeth everi photo meghan kate harri william centenari armistic servic',
 'ben affleck gift pet pooch sourc tell us final day rehab',
 'kyli jenner say daughter stormi look like',
 'zayn desper defend girlfriend gigi hadid',
 'angelina joli talk brad pitt bell palsi vaniti fair cover stori',
 'cara delevingn claim harvey weinstein tri kiss want take part threesom hotel suit',
 'watch britney spear end la vega resid new year eve perform',
 'better call saul',
 'kendra wilkinson say sign last divorc paper husband hank baskett',
 'kim kardashian beg tristan thompson unblock instagram',
 'ed sheeran admit abl bed hot women taylor swift',
 'jennif lopez snub vanessa hudgen second act set',
 'may page amnayzh news',
 'pari hilton talk kim kardashian clone new yeezi campaign exclus',
 'selena gomez weeknd date timelin everyth',
 'realli hurt jay z open alleg feud kany west',
 'fixer upper star chip joanna gain return tv new discoveri network',
 'know matthew rhi strip mother premier ok',
 'tri starbuck zombi frappuccino sure feel',
 'kim kardashian slam ridicul bikini instagram asham',
 'netflix stop stream marvel movi',
 'ariana grand jimmi fallon break record tonight show takeov movi televis',
 'alex rodriguez share never seen photo jennif lopez sweet birthday post',
 'rob pattinson still care deepli kristen stewart get back togeth parti reunion',
 'venu william driver clear fatal crash',
 'last black unicorn tiffani haddish amazon com book',
 'bachelor paradis taylor nolan derek peth split',
 'saturday save jennif lopez crop sweater',
 'celebr marriag kendra wilkinson take wed ring break instagram',
 'kim kardashian blond dye hair pink check vid',
 'meryl streep nicol kidman feud big littl lie set report closer weekli',
 'bekah explain mother report miss bachelor film actual big deal video',
 'scheana shay felt harsh cold toward mike shay reunion',
 'hurrican maria could billion storm puerto rico',
 'way riverdal gossip girl essenti show',
 'next bachelor peter krau tweet believ',
 'ivanka trump us weekli cover meme',
 'sparknot handmaid tale plot overview',
 'ed sheeran say broke arm bike accid',
 'polic recov elizabeth smart arrest abductor',
 'kelli rohrbach cosi shirtless beau steuart walton malibu',
 'tarek christina el moussa produc new hgtv show chi town flip',
 'walk dead season reason rick grime actor andrew lincoln quit seri',
 'ellen degener wife portia de rossi make cri th birthday gift',
 'total bella renew season e',
 'lebron jame sport star gone hollywood tussbal',
 'sag award milli bobbi brown wear convers sneaker',
 'halsey gush g eazi heart break love everyth',
 'brad pitt angelina joli divorc stall relationship neri oxman blame',
 'rihanna give flash cleavag nyfw show',
 'time kim kardashian absolut savag sister kuwtk',
 'wear gingham spring',
 'coco austin daughter chanel mermaid bikini bahama',
 'gwyneth paltrow pose topless mud goop first issu',
 'media wall vs step repeat vs logo wall',
 'full list hip hop award winner',
 'watch ryan gosl tell save jazz saturday night live season kick',
 'joanna gain expect fifth babi feel like first time pregnant',
 'billi bush break silenc trump access hollywood tape nbc comeback plan exclus',
 'darren aronofski',
 'see meghan markl navi princ harri rush princess eugeni royal wed',
 'ashley benson channel olsen twin plu beauti essenti',
 'michael strahan sara hain host abc new gma hour',
 'watch live tim kain corey stewart meet first u senat debat virginia',
 'singer tina turner thanksgiv first time year thank presid god bless support support tina american presid donald j tru',
 'britney spear',
 'dad bag',
 'gal gadot play box lie tonight show insert lasso truth joke',
 'gwen stefani still smitten blake shelton never tri chang exclus',
 'brad pitt relationship neri oxman',
 'estat carri fisher debbi reynold sell home person item',
 'former realiti star jon gosselin reveal celebr sextuplet big mileston birthday',
 'chan tatum cheat jenna dewan actor admit struggl balanc work famili',
 'j balvin reveal relat women viral video claim aunt',
 'heath ledger',
 'tyler henri speak kristin cavallari late brother',
 'serena william channel hollywood glamour star stud rehears dinner',
 'latest three billboard win best drama film globe',
 'chloe lukasiak maddi ziegler still friend danc mom star lot',
 'gordon ramsay say drop lb save marriag',
 'erika girardi react eileen davidson exit real housew beverli hill',
 'taylor swift teas tour creat ticket buy initi fan',
 'mariska hargitay shine law order svu sneak peek mess mama bear benson',
 'normani kordei danc star twist ankl injuri affect dwt',
 'watch new mari poppin return featurett goe behind scene disney sequel',
 'justin bieber selena gomez rekindl romanc end promis marriag',
 'jennif lawrenc',
 'serena william share favorit video daughter alexi olympia',
 'wwe brie bella give birth reason birdi joe million dollar babi',
 'ami schumer nation bikini day gram everyth',
 'celebr share tribut victim barcelona terror attack',
 'kate middleton princ william may celebr princ georg birthday caribbean island',
 'nicki jam el ganador star singer premier netflix telemundo',
 'mike tyson offer seriou ca h fight russian dictat vladimir putin',
 'brad pitt moonlight furnitur busi',
 'ashton kutcher guy night show bro wilmer valderrama danni masterson',
 'jimmi kimmel blast trump graham cassidi rd night attack republican healthcar bill',
 'even jenel evan gun incid teen mom controversi histori',
 'jessi jame decker get hot bother watch eric decker yard work eric jessi',
 'selena gomez pregnant weeknd babi race marri report',
 'khloe kardashian tristan thompson split insid passion fight',
 'gwen stefani call blake shelton',
 'kim kardashian apolog controversi aaliyah halloween costum see color home',
 'insid danica patrick post race life love waffl build brand bottl wine',
 'kim crumbl marriag kany absolut noth anniversari',
 'see courtney love chew sceneri menendez brother movi trailer',
 'franc bean cobain hope dad would proud',
 'khloe kardashian awe sister kim kardashian best bodi ever',
 'rob kardashian show support ex rita ora girl backlash',
 'alicia key year old son amaz beatbox watch cute video',
 'hottest celebr gossip entertain news ghana worldwid plu lifestyl',
 'michael phelp wife nicol throw shower babyshark',
 'kate middleton princ william show pda like princ harri meghan markl',
 'gif game throne jon snow shrek donkey leav shook',
 'jayz daze confus',
 'crazi detail behind make halloweentown',
 'ryan seacrest pack pda girlfriend shayna taylor getaway itali',
 'newlyw pippa middleton jame matthew seen lax',
 'spice girl',
 'labor day need protest',
 'shawniec jackson jepht pierr welcom daughter laura denis',
 'scott disick reportedli consid write kardashian tell million',
 'angelina joli attend royal wed specul',
 'jennif aniston justin theroux real reason celebr coupl split',
 'simon cowel rush hospit accid london home',
 'watch jenna dewan tatum total gush husband chan tatum proud',
 'ariana grand pete davidson timelin relationship',
 'kerri washington love part pixar famili even kid get yet',
 'kaskad pool parti do ts guy elmo floati',
 'manchest bomber link brussel man hat',
 'rumor bust kati holm breakup jami foxx joshua jackson',
 'chanel iman sterl shepard expect babi girl',
 'pari hilton think could like princess dianna sex tape',
 'jay z admit marriag beyonc truth',
 'jennif lopez alex rodriguez rais million puerto rico',
 'us report kim kardashian announc divorc',
 'rihanna hassan jameel romanc timelin',
 'kate middleton wear emilia wickstead plaid skirt raf christma parti',
 'manu x machina experi',
 'stephen colbert jimmi kimmel guest thursday night',
 'chri harrison next big step get anoth bachelor paradis exclus',
 'danc star movi night give one coupl hollywood happi end',
 'find real housew orang counti return',
 'hugh hefner',
 'jay z leav nightclub staff tip peopl happi',
 'brad pitt get marri',
 'espi vote best male athlet',
 'happi anniversari john krasinski emili blunt reliv cutest moment',
 'american idol renew season abc judg host ryan seacrest set return',
 'grey anatomi unexpect way sara ramirez return season final',
 'kristen bell frozen prompos made dream come true',
 'ah apocalyps biggest question need answer final',
 'gwen stefani got dump blake shelton jealousi drama exclus',
 'best new beauti product week',
 'jennif lopez engag alex rodriguez despit ring specul',
 'khloe kardashian given birth girl need know possibl name',
 'connect peopl news',
 'see everi celebr royal wed princ harri meghan markl',
 'nsfw savagexfenti xccessori accord rihanna',
 'seen bonu jona franki jona late',
 'david victoria beckham shut divorc rumor',
 'talk moment super bowl',
 'kim kardashian dye pink hair brown khloe kardashian babi shower',
 'ryan phillipp ex girlfriend lawsuit everi one accus alleg fals',
 'tom bradi kiss gisel costa rica super bowl loss',
 'michel obama releas memoir novemb cb new york',
 'natalya tell total diva season',
 'gotti film',
 'singer halsey freez egg endometriosi need aggress',
 'sza debut album ctrl gone platinum',
 'golden globe look made statement cost less',
 'winner nomine categori',
 'bafta winner list',
 'committe judiciari',
 'pregnant khloe kardashian hit tokyo kim kourtney sister trip',
 'look like sophi turner joe jona serious commit',
 'let astrolog help discov best spring fashion trend',
 'flash season trailer featur cicada surpris visit barri daughter',
 'wed gown tv film would heavenli met gala',
 'watch ellen degener scare crap sam smith halloween prank',
 'jennif lawrenc say mother led darren aronofski split',
 'rihanna blowout fight hassan jameel smoke weed',
 'keep kardashian',
 'u senat john mccain',
 'alpha male mad vote elit',
 'bachelor bekah martinez saw ari elimin',
 'pictur prove meghan markl princ harri children quit yet',
 'presid obama cri drop malia harvard like open heart surgeri',
 'kany west post tribut lamar odom diss tristan thompson cheat khloe',
 'fox news shepard smith lie lie lie russia meet',
 'ryan plan includ billion medicar cut say stephani cutter',
 'heroin u come across mexican border rob portman say',
 'gigi hadid send love taylor swift attend reput tour proud',
 'johnni depp su ex bodyguard unsaf work condit unpaid wage',
 'ellen degener cri receiv best birthday gift portia de rossi',
 'debunk week tabloid stori juli',
 'khloe kardashian done',
 'dream kardashian get halloween spirit new photo',
 'crown season first look helena bonham carter princess margaret',
 'steve harvey said apolog brutal staff rule includ attempt walk wait hallway speak',
 'see jurass world fallen kingdom need watch rap recap',
 'dua lipa point sexism music industri british gq',
 'hollywood celebr harvey weinstein academi expuls onlin glee',
 'paul rudd love show kid inappropri movi',
 'arrang kyle west four word hater bash new movi let eat cake',
 'tyler henri connect coco late grandmoth make joke quot sexual quot song quot shoe freak quot',
 'california adventur pixar transform close california screamin',
 'kourtney kardashian pregnant babi',
 'good place recap true north',
 'robert pattinson desper want bond kristen stewart',
 'selena gomez wizard waverli place brother david henri return disney fourth juli',
 'toni award complet list nomin',
 'big brother cb respond inappropri behavior offens comment cast member',
 'public financi disclosur report',
 'new netflix march jessica jone collater benji',
 'charli heaton natalia dyer break stranger thing coupl reportedli split season',
 'big bang star kaley cuoco love wine lead awkward incid',
 'billboard award jenna dewan domin red carpet',
 'bold type return new season definit work',
 'miley cyru liam hemsworth secretli get marri',
 'sam hunt spiritu strength marri life feel littl bit taller wear wed ring',
 'selena gomez believ justin bieber soulmat destin togeth',
 'la la anthoni husband carmelo reconcil almost two year call quit',
 'transform cement face woman botch debut new look',
 'royal babi princ william duchess kate new princ name loui arthur charl',
 'sofia vergara confirm husband joe manganiello secret nerd',
 'despit report blog pictur wordpress',
 'hot felon jeremi meek wife tear emot interview chloe green cheat scandal',
 'khlo kardashian want marri tristan thompson amid report spend qualiti time cleveland',
 'jenna dewan natur eyebrow hack',
 'rachel bloom bought gucci dress emmi award',
 'demi lovato beat shazam episod pull fox schedul overdos report',
 'john mahoney',
 'new roseann queer spectatorship',
 'photo prepar royal wed princ harri meghan markl',
 'nikki bella hid first marriag john cena react found',
 'real housew orang counti',
 'jame van der beek would diplo',
 'cameron diaz',
 'selena gomez share photo date night weeknd',
 'nanci juvonen',
 'emma watson donat million anti sexual harass campaign',
 'donal logu miss transgend daughter found',
 'shame actor terri crew detail alleg sexual assault',
 'cole sprous lili reinhart relationship timelin',
 'kate middleton pregnant twin girl',
 'thing might know find nemo',
 'brad falchuk net worth',
 'gisel bundchen share shot tom bradi decor tree daughter vivian',
 'introduc easi diy natur toner',
 'janet jackson visit hurrican harvey victim kick state world tour',
 'miss old kany happen rap complex star',
 'reveng star ashley madekw show leg cut vintag denim hotpant',
 'help guid khlo kardashian tristan thompson cheat scandal',
 'sag award memoriam honor david cassidi',
 'princ william may reveal gender kate middleton third child',
 'emili blunt join disney jungl cruis drink tequila rock',
 'elizabeth hurley gush jennif lawrenc look like versac',
 'kate middleton twin princ william say likelihood',
 'britney spear sex tape',
 'nicol kidman prove clap normal seal like oscar mishap internet hyster',
 'complet list live die aveng infin war',
 'gwen stefani reveal hilari christma gift get blake shelton',
 'kardashian desper tri rescu kyli jenner new show slam fakest realiti show ever',
 'sarah jessica parker favorit sex citi memori',
 'time senat job congressman mike honda medium',
 'latest news view gossip pictur video',
 'bachelor paradis return season highest rate ever full episod',
 'lisa rinna daughter amelia gray hamlin reveal battl anorexia',
 'khloe kardashian slam reveng bodi contest fake cri tear perfect act',
 'kasich woman intellig enough keep leg close entrust abort decis',
 'savannah chrisley split luke kennard dodg bullet',
 'ramona singer perform keli milkshak lip sync battl',
 'orlando bloom son cutest reaction see pirat caribbean first time',
 'reliv jessi jame decker eric decker sexiest eric jessi moment makeout session bubbl bath',
 'darnel nicol get shock news new beau wag miami sneak peek somebodi use smash',
 'lesli jone comedian',
 'jami dornan dakota johnson horribl bed forc reshoot entir fifti shade darker sex scene catastroph',
 'blake shelton realli think gwen stefani split rumor say sourc',
 'jennif aniston join sandra bullock bryan randal dinner see pic',
 'alyssa milano viola davi star speak women march',
 'tina fey play game involv two e recreat ghost potteri scene',
 'alan thick widow say plan babi prior grow pain star unexpect death',
 'long act liam hemsworth heart set model career',
 'offici web site',
 'amber rose sleep hour home invas',
 'takeaway curri game throne elabor disguis young royal life kensington palac',
 'beyonc stylishli celebr jay z birthday follow infidel admiss',
 'shia labeouf tweet apolog deepli asham behavior',
 'princ harri meghan markl relationship timelin',
 'justin theroux',

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[9076, 3375, 1036, 6383, 9148, 3118, 631, 9768, 92, 6653],
 [5988, 6497, 9046, 8831, 8300, 6872, 2193],
 [6248,
  2601,
  7449,
  6947,
  798,
  6605,
  4491,
  7778,
  9436,
  1497,
  2394,
  7050,
  2158,
  9824,
  7877],
 [220, 4881, 538, 7672, 5157, 1932, 3601, 2],
 [4877, 757, 8079, 4372, 5580, 3855, 587, 7607, 7968, 3644, 3136, 3252, 2662],
 [6229, 517, 4870, 4393, 3359, 3056, 2554, 7539, 1261],
 [4218, 1234, 2713, 6421, 359, 1260],
 [868, 8560, 6080, 9931, 981, 6166, 8727, 5141, 2147, 2752],
 [6435, 9923, 6635, 2334, 7328, 6106, 6217, 2950, 2505, 7653, 1497, 2394],
 [5895, 2007, 5040, 9777, 8505, 5446],
 [3416, 5535, 2394, 6790, 6690, 4355, 2450, 2856, 9061],
 [7261, 279, 9379, 5470, 9988, 3932, 3434],
 [7301, 3154, 1216, 974, 6799, 6605, 3177, 128, 8871, 1808, 7916, 2191],
 [2865, 8545, 2082, 4116, 8018, 3763],
 [358, 857, 3239, 9510, 6604],
 [6804, 8472, 4262, 4409, 3931, 7723, 2213, 6536],
 [9186, 4697, 1382, 8424, 5040, 9697, 8833, 5148, 1830, 5761],
 [6132, 8524, 4402, 3734, 5871, 6057, 8915],
 [4930, 6390, 4840, 3416, 1372, 6947, 2369, 6696, 2303],
 [1401, 5850, 251, 1433, 2213, 2041, 4990, 8727],
 [1818, 7867, 8692, 1615, 9613, 2179],
 [3449, 3601, 2391, 2903, 9236, 4931, 1455, 328, 1455, 9193, 5151, 1488, 2256],
 [8725, 8281, 3234, 2469, 8366, 6817, 6076],
 [9697, 4224, 9621, 2955, 3405, 6106, 9613, 9622, 5958, 111, 4741, 3615],
 [9056, 8217, 5161, 2356, 1043, 1171, 6049, 8172],
 [4790, 9273, 372, 5290, 2193, 6458, 4782, 6543],
 [1818, 42, 7645, 4123, 1556, 1748, 5284],
 [4748, 1891, 3493, 6080, 1264, 618, 6331, 7328, 9137, 3580],
 [1554, 8462, 1674, 2334, 1410, 4489, 1977],
 [9854, 7460, 3897, 7173, 6224, 468, 4344],
 [2893, 9564, 7403, 3154, 162, 6224, 7717, 9362],
 [5213, 4930, 4239, 5762, 1231, 8829, 2679, 2407],
 [232, 4332, 4990, 5845],
 [2926, 4536, 4852, 8927, 5829, 2999, 1514],
 [1415, 9004, 5115, 3863, 5360, 4408],
 [8927, 5829, 8801, 1631, 2380, 9148, 1669],
 [9715, 8962, 9579, 9775, 4826, 1390, 8751, 2256],
 [1554, 9061, 2334, 9826, 7093, 831, 6639, 9058, 1241],
 [341, 3049, 4561, 5746, 2539, 5161, 5788, 1043, 4365],
 [8355, 4950, 342, 6166],
 [9697, 8944, 5762, 2883, 640, 2072, 7397, 8295, 303, 8079],
 [8560, 817, 1669, 588, 5217, 686, 286, 8172, 7918],
 [9236, 4931, 686, 733, 4053, 1013, 5198, 1525],
 [8386, 618, 2807, 486, 2239, 4512, 6166],
 [9056, 8706, 5964, 8988, 9622, 8682, 1733, 4698, 7422],
 [8046, 2394, 3135, 372, 6224, 1003, 3601, 9611, 9564, 4707, 442],
 [3783, 4930, 1626, 7853, 717],
 [1874, 5213, 4930, 4239, 4950, 8545],
 [5213, 4930, 6679, 7962, 1850, 4239, 3981, 4169, 8715, 4576, 4710, 495],
 [2977, 9753, 6748, 3663, 9101, 7336, 9803, 5210],
 [2688, 3080, 7197, 4092, 5040, 2029, 5527],
 [5653, 6973, 757, 8562, 6288, 9674, 6683, 4930, 3615, 9404, 67, 1554],
 [112, 102, 8880, 9777, 9046, 8751, 2, 9236, 4667, 4707],
 [8524, 5285, 5840, 2394, 4776, 6273],
 [4356, 9536, 9610, 9015, 1069, 2090, 2586, 6076],
 [4646, 3657, 3783, 4930, 6018, 1366, 5653, 8562],
 [5290, 1054, 4381, 2886, 9982, 3029, 4776],
 [3678, 7460, 481, 3573, 2458, 6090, 1144, 6748],
 [9236, 4931, 1043, 111, 1433, 3644, 6106, 1455, 9193, 1261],
 [2251, 243, 8322, 8878, 3152, 6331, 6014, 7955],
 [549, 5528, 1194, 3277, 5762, 7717, 9362, 4116, 3642, 7723, 1275, 6653],
 [3141, 6069, 5945, 3618, 8887, 8079, 962, 5161, 6421, 2167],
 [6888, 8543, 4092, 4857, 4425, 9379],
 [5378, 8739, 2408, 4525, 5816, 757, 9613, 1945, 6653],
 [82, 8386, 3889, 9347, 5439, 8079, 4710, 1655],
 [6213, 1734, 5997, 5148, 5997, 9920, 7747, 9862, 5958],
 [9779, 2829, 9031, 7994, 2789, 5871],
 [6280, 8592, 6544, 251, 8986, 4570, 603],
 [8553, 4643, 291, 1063, 8366, 4763, 8786, 8915, 4218, 9622],
 [7955, 9273, 686, 402, 6701, 4491, 8829, 4196, 5337, 6029],
 [8811, 7821, 6414, 6229, 517, 990, 3359, 3056, 1554],
 [5212, 6992, 4484, 6659, 4126, 901, 4930, 3601, 7539],
 [3153, 4264, 5686, 2051, 1492],
 [3359, 2408, 7659, 8927, 5829, 4676, 2963],
 [5174, 7050, 6909, 2878, 2926, 4536, 1957, 6444, 5657, 1674],
 [1631, 9273, 6772, 1659, 3534, 8828, 2824, 748, 7005, 4666],
 [2041, 2429, 7955, 2391, 9236, 328, 9193, 5699, 8024, 4741],
 [2956, 9999, 2878, 4655, 2572, 495, 4844, 6680, 1144, 8751, 4513],
 [3511, 1674, 5762, 5040, 376, 2193, 9642],
 [7365, 8305, 7277, 832, 4291, 8562],
 [4990, 5845, 4092, 1401, 5850, 9536, 6318, 5488, 591, 8918, 8882],
 [3259, 4070, 5958, 8927, 5829, 2277, 5288, 111, 1815, 1878, 2612, 1556, 6608],
 [1554, 8553, 4643, 5788, 1372, 6947, 2045, 9613, 8079, 1575, 5284],
 [9136, 5141, 191],
 [3278, 1711, 5762, 1197, 8240, 6748, 986, 2461, 4131, 4909],
 [5213, 4930, 5781, 2772, 5212, 2831, 6331],
 [445, 3814, 9579, 7834, 1656, 990, 3891, 5558, 4823],
 [2926, 8962, 7789, 487, 7942, 5017, 1492, 3521],
 [4448, 5330, 9085, 4477],
 [1115, 6732, 4092, 5213, 4930, 6594, 9613, 6577, 7658, 1261],
 [3241, 2983, 5846, 6166, 2568, 5631],
 [1043, 1553, 2316, 105, 251, 2963, 183, 1850, 4239],
 [1740, 5580, 2394, 8591, 481, 3580, 9173, 9834, 9613, 2766, 7902],
 [8829, 7625, 8811, 2484, 5745, 8892, 2280],
 [2277, 5698, 9852, 5601, 8661, 2900],
 [5213, 4930, 9188, 1090, 1894, 6331, 1432],
 [9243, 778, 8024, 3283, 9694],
 [8011, 1821, 3797, 1934, 7906, 6903, 3618, 5161, 2640, 9694, 4339],
 [9616, 7565, 4389, 1642, 5790, 7955, 2926, 8962, 6947, 798, 7328],
 [5689, 9409, 3569, 2051, 2075, 6967, 2474, 1433, 2213, 2041, 5796, 92],
 [4522, 9193, 147, 5964, 7723, 9068],
 [8240, 3237, 2329, 2090, 9064, 5217, 1771, 372],
 [9854, 5719, 5558, 2940, 7407, 4647, 2239],
 [8540, 4356, 2926, 8962, 1592, 1655],
 [9273, 1772, 3278, 1711, 1815, 2256, 5796, 7906, 6331],
 [5213, 4930, 4633, 169, 6273, 1818, 6252, 7991],
 [4303, 5846, 6690, 1345, 183, 2408, 2508, 359, 3521, 9622, 6716, 4965],
 [6106, 1091, 5745, 9622, 4593, 9854, 71, 755, 2408, 793, 6653],
 [3541, 144, 5110, 3264, 2345, 8033, 5061, 144, 92],
 [9527, 1665, 1448, 5266, 7020, 28, 590],
 [38, 4408, 4877, 757, 1701, 5161],
 [1126, 9854, 2257, 233, 9497, 7264],
 [7900, 1242, 6680, 4965, 8918, 9381],
 [1392, 6390, 5038, 9336, 4125],
 [445, 3814, 5762, 3800, 2690, 4523, 6457],
 [6122, 6686, 6588, 121, 5306, 6316],
 [8551, 808, 5714, 6049, 5761, 3556, 7863, 9317],
 [8472, 7870, 4262, 4409, 127, 9613, 1194, 5161, 5506, 3110, 4911],
 [5264, 4189, 8545, 6804, 6170, 1301, 9943, 4784, 4211, 6957, 8774],
 [8181, 6439, 6544, 8434, 9321, 8563, 6635, 1419, 2519, 798, 2878],
 [9134, 4587, 9004, 8545, 2422],
 [8139, 7543, 3238, 2394, 8121, 9379, 298],
 [6453, 9046, 6233, 6644, 6095, 686, 2228, 1645],
 [1869, 3839, 9134, 7238, 2165, 7906, 4115, 5631],
 [1401, 5850, 4990, 5845, 6748, 6748, 3601, 1284, 3102, 7876],
 [6742, 2789, 853, 3642, 5637, 5161],
 [7653, 5213, 4930, 4148, 7406, 1241, 649],
 [686, 8811, 1278],
 [85, 9827, 5040, 26, 8111, 1894, 6691],
 [2379, 5420, 9556, 7588, 4774, 1690, 2334, 3857],
 [5784, 1161, 9974, 286, 3273, 9974, 4200, 1161],
 [7301, 8355, 2186, 2405, 9046, 6599],
 [1554, 9056, 3933, 4844, 4356, 8627, 8540, 3763, 2408, 8545, 836],
 [481, 3580, 3405, 6057, 6106, 2900, 9642, 2334, 7653, 3644],
 [6061, 2601, 7906, 5220, 1242, 2067, 9379, 2269, 8453, 7994, 6464, 1261],
 [9015, 1355],
 [5174, 2391, 2903, 3624, 1455, 328, 2538, 3523, 9317, 1488, 2256],
 [6790, 1770, 3489, 7486, 4344, 5691, 5468, 1701],
 [8386, 4427, 3953, 4971, 5602, 9651, 9613, 4601, 9770],
 [1554, 2408, 478, 5535, 3663, 2474, 4122, 2334, 2441, 8973, 3994, 7365],
 [4881,
  5620,
  7450,
  1071,
  2334,
  7653,
  8079,
  6573,
  8572,
  459,
  1173,
  4218,
  4218,
  5620,
  8284,
  8572,
  1594,
  5378,
  3477],
 [8553, 4643],
 [589, 5486],
 [8783, 4799, 4770, 8752, 359, 3618, 5161, 1862, 3280, 8346, 6414],
 [6229, 517, 3569, 9925, 3359, 3056, 1642, 2277, 3644, 1261],
 [1401, 5850, 3601, 1284, 3102],
 [7917, 5862, 1799, 4642, 4021, 806, 1626, 5602, 5076],
 [8692, 5208, 2394, 286, 7452, 6224, 9273, 7654, 2408, 9274, 798],
 [7364, 4326, 9775, 8071, 8275, 9943, 9579, 4799, 3478, 1430, 3615],
 [5378, 8739, 6224, 7002, 3891, 5442, 6653, 5958, 2],
 [6838, 3294],
 [3154, 1216, 8523, 3177, 128, 3508, 1808],
 [9779, 9193, 3489, 9379, 1978, 2394, 1423, 9338, 1682],
 [7723, 5439, 1947, 2175, 8831, 7539, 71, 4226],
 [7056, 723, 3621, 3261, 3569, 1763, 5840, 9564, 2394, 1842],
 [8074, 6196, 5762, 1615, 9362, 4356, 1772],
 [2979, 7173, 2066, 505, 4722, 4198, 3118, 631, 6375, 9436],
 [5558, 4823, 4045, 8692, 280, 3364, 8226, 4868, 9324],
 [8953, 5644, 3503, 8206, 5777, 8636, 5775, 1072, 9638, 2688, 4534, 1770],
 [369, 4910, 5840, 2394, 6103, 6683, 6536, 1974, 2865],
 [1554, 9613, 2553, 4490, 9173, 4976, 905, 1809, 2872, 8018, 607],
 [2365, 1419, 3241, 2983, 5761, 8375, 5788, 3646, 1772],
 [2926, 4536],
 [9779, 9193, 4389, 6908, 6653, 5040, 1826, 8148],
 [9020, 3241, 4587, 2789, 5871, 6804, 8710, 9531, 2170, 9921, 6106],
 [8101, 1924, 3576, 1894, 8751, 7069, 5631],
 [9273, 4389, 6194, 2303, 1803, 529, 2621],
 [9236, 4931, 1455, 9193, 4448, 9273, 1455, 3123, 798, 5678, 9867],
 [622, 9919, 4262, 6379, 2394, 4881, 8892, 9243, 4779],
 [5061, 9233, 6212, 2179, 7168, 7427, 984, 4355, 3536, 9631, 5502],
 [1401, 5850, 6425, 909, 1974],
 [474, 5548, 767, 3763, 5161, 144, 2608, 5929, 4291, 2089],
 [3797, 713, 4852, 1242, 7705, 4697, 9567, 3763, 2621, 7, 9580, 3304],
 [9301, 7318, 7313, 5532, 1733, 2893, 9564, 9832, 1292],
 [4697, 7543, 3290, 1433, 990, 8853, 1554, 1048, 3290, 3523, 1430, 1048, 4697],
 [3241, 2983, 3644, 5846, 6106, 1487, 9061, 9622],
 [1927, 4930, 2772, 5212, 2239, 3141, 5884, 984],
 [6229, 517, 5141, 3359, 3056],
 [5213, 4930, 4388, 9832, 8061, 7787, 7918, 5174, 4381, 1626],
 [3141, 2095, 7668, 7328, 1487, 8887, 4115, 3535, 6531, 1269, 90, 2087],
 [5213, 4177, 1772, 1850, 4148, 9910, 1753],
 [5174, 2029, 4115, 4213, 1870, 8187, 1808, 9694, 1592],
 [7227, 9556, 5244, 5605, 589, 5290, 4856],
 [1927, 4930, 2721, 1241, 5213, 4930, 8831, 1264, 1410],
 [5689, 4930, 5161, 4218, 221, 8970, 1542, 757, 3356],
 [2807, 6600, 8079, 6408, 1830, 4341, 2952, 1554, 3439, 6653],
 [9829, 9273, 4877, 9614, 4477, 382, 8106, 5691, 7368],
 [8386, 510, 6544, 6690, 1077, 7068, 9887],
 [9236, 4931, 1455, 9193, 5161, 5121, 9642, 1455, 328, 2391, 2903],
 [301, 3130, 5499, 286, 8172, 770, 987, 5148, 7731],
 [9532, 1483, 5070],
 [5963, 3415, 1809, 6635, 9693],
 [9056, 4240, 166, 5121, 832, 2539, 5558, 9899, 71],
 [7982, 2698, 4931, 7543, 7625, 5790, 3021],
 [9802, 757],
 [7667, 8751, 9351, 3288],
 [1818, 9864, 1103, 3038, 2698, 5040, 9108, 5989],
 [5653, 8562, 3006, 1054, 7610, 4930, 4844, 2170],
 [4990, 5845, 8880, 1488, 2256, 2351],
 [2926, 5988, 2365, 1583, 3118, 6804, 9273, 8796, 2239],
 [552, 9589, 2538, 4169, 6457, 404, 1626],
 [1554, 8071, 8275, 4326, 9134, 3839, 2461, 7364, 4326, 4856],
 [8011, 1821, 5011, 4722, 2568, 3601],
 [643, 6250, 4115, 1878, 8689, 3615, 9301, 1231, 1433, 641],
 [540, 7601, 5796, 8955, 5349, 767, 3046, 9141],
 [3122, 4045, 8580, 6520, 3754, 7110],
 [8727, 2308, 9697, 4224, 7662, 9621, 2955, 6546, 9864],
 [26, 5388, 6156, 4023, 3405, 6106, 757],
 [1115, 6732, 9945, 1448, 9642, 3523, 7936, 1224, 2269],
 [2316, 105, 9579, 1772, 4950, 8346],
 [2926, 8962, 9616, 7565, 1912, 2170, 28, 590],
 [6680, 9622, 5213, 4930, 7867, 6748],
 [6742, 2444, 6877, 8375, 2568],
 [9236, 4931, 686, 5194, 7205, 458, 4693, 9596, 6909, 5796],
 [7223, 6242, 3654, 7959],
 [2185, 5540, 3797, 713, 3764, 9612, 3763],
 [8548, 7251, 1126, 2408, 286, 1433, 9674, 9854, 5719, 1261],
 [5840, 2394, 9694, 3763, 2789, 4491, 8796, 9379, 6224, 5788],
 [4112, 3118, 631, 3377, 1234, 9173],
 [6858, 3145],
 [2316, 105, 5148, 3652, 6267, 6734, 5988, 6224],
 [1401, 5850, 1433, 9061],
 [631, 4214, 8831, 3174, 4013],
 [6224, 1753, 3667, 9136, 9734, 6568, 1150, 3692, 4525],
 [8284, 3311, 9004, 8545, 9651, 2559, 5602, 9056, 4240, 3521, 9173],
 [8522, 1686, 1701, 38, 3953, 899, 9173, 8545, 1144],
 [6967, 9536, 4560, 7870, 1669, 5816, 8738, 6022],
 [398, 5004, 4933, 4822, 9351, 8641, 1144],
 [6229, 517, 4870, 4393, 3359, 3056, 2554, 7539, 1261],
 [8831, 9613, 5468, 4776, 4116],
 [2926, 8962, 5921, 9616, 7565, 9862, 5796, 2351],
 [1927, 4930, 3734, 5871, 757, 9351, 8829, 3583, 4666],
 [4820, 5988, 4477],
 [5174, 2429, 9273, 1488, 2256, 1455, 328, 2391, 2903],
 [7467, 7734, 2050, 901, 6742],
 [5790, 2618, 9519, 367, 9519, 3508],
 [9186, 8731, 5711, 6080, 6748, 8727],
 [4092, 4525, 4824, 622],
 [5213, 4930, 169, 1818, 6273, 6095, 1927, 4930, 6106, 7068],
 [9056, 8217, 221, 832, 4644, 2429, 4491, 9148, 2963, 8988],
 [4297, 2799, 5288, 9807, 614, 1484, 4824, 622, 5814],
 [3314, 5384, 5081, 481, 505, 8869, 9613, 4277],
 [1310, 4844, 9134, 1255, 8545],
 [1700, 71],
 [4881, 1869, 2973, 6985, 9402, 9351, 6842],
 [796, 7738, 6175, 6702, 8121, 5735],
 [5406, 4226, 2193, 1669, 4100, 427, 549],
 [6599, 4960, 6017],
 [5073, 6599, 8355],
 [2685, 2302],
 [3644, 1927, 4930, 751, 4776, 5213, 3783, 1241, 6683],
 [2193, 9642, 8496, 7450, 9531, 9519, 8885, 5750],
 [6946, 6403, 3462, 9192, 8831, 1278, 7958, 1659],
 [853, 8545, 1592, 3600, 7776, 8340, 5370, 9136, 5040],
 [2256, 3489, 9834, 71, 5290, 6516, 482, 86],
 [1554, 8181, 6439, 4710, 7272, 8520, 5997, 7787, 4781],
 [2926, 4536, 5762, 5745, 1338, 9015, 1355, 2239],
 [6742, 3180, 984, 2444, 6877, 3930, 2346],
 [1507, 4930],
 [2441, 8973, 3667, 6524],
 [5236, 3174, 6261, 4214, 9134],
 [9854, 6106, 9010, 5183, 4237, 2030],
 [2080, 9267, 2391, 2903, 1455, 328, 2285, 6957, 641],
 [8572, 5384, 1419, 1615, 2496, 4507, 9642, 251, 2165, 8483],
 [1850, 4239, 7328, 6194, 2397, 6856, 922, 2772, 5212, 9775, 1927],
 [1215, 4477, 4023, 5997, 359, 359, 359, 4321, 4122],
 [9056, 6464, 7312, 5266, 695, 1382, 5762, 9410, 6637],
 [3509, 2441, 8738, 431, 2049, 5677, 5689, 3318, 5762],
 [4291, 8562, 7449, 4115, 5558, 4823, 8880, 424, 8692, 4856],
 [8725, 8281, 3864, 221, 4636, 3538, 1430, 3263, 9309, 3969],
 [8181, 6439, 1419, 3585, 8831, 798, 2878, 8434, 9321, 8563],
 [4225, 4116, 9726, 8882, 9567],
 [1927, 4930, 1652],
 [5816, 4930, 1433, 7787, 7453, 9613, 7955],
 [2406, 8545, 2334, 2193, 3351, 2241, 3159, 3523, 9827],
 [6155,
  8927,
  4228,
  4388,
  9007,
  6267,
  1132,
  7312,
  8000,
  5264,
  5842,
  5947,
  8523],
 [5174, 7872, 7968, 6047, 1037, 9351, 1554, 4599, 7315],
 [5797, 173, 8004, 6791, 1275, 7051, 5151, 8482],
 [9379, 9273, 8927, 5829, 7872, 7824, 6111, 7018],
 [9015, 624, 4115, 5161, 1231, 1932, 9694],
 [5383, 7261, 4239, 712, 8412, 8650, 8997, 9613, 9694, 6946, 743, 4802],
 [3154,
  1216,
  4820,
  85,
  3508,
  7786,
  6635,
  6414,
  752,
  1542,
  752,
  9217,
  752,
  1703,
  896,
  752],
 [428, 3319, 8689, 7488, 5597, 428, 8766],
 [3783, 4930, 3644, 6106],
 [6458, 3348, 7315, 6022, 2947],
 [4355, 9409, 8305, 111, 6645, 6967, 2474],
 [3241, 2983, 2017, 9519, 3348, 1808, 9186, 1216, 9173, 8018, 8371, 9567],
 [9777, 9046, 8833, 8355, 8505],
 [2408, 1808, 8869, 764, 1932, 5713, 5906, 3505, 6756, 8508],
 [1826, 1348, 1768, 9622],
 [9613, 9243, 3074, 3170, 8793, 1756, 3121],
 [3234, 4879, 6665, 2245, 7906, 526, 6773, 8796, 3006, 2239, 8545],
 [2408, 4286, 2394, 5874, 4920, 4115, 2087, 220, 2975, 1733],
 [1947, 9046, 8071, 8275, 8282, 8300, 6872],
 [7844, 3390, 9173, 9613, 8545, 5185, 1430],
 [8265, 3095, 3823, 9399, 5505, 1433, 9061],
 [8520, 98, 1547, 2946, 9061, 8887, 2900, 2508, 3767, 6537, 686, 2256, 5796],
 [3241, 2983, 7264, 2365, 1419, 8346, 3815, 2041],
 [1372, 1372, 82, 2461, 2790, 4827, 172, 6819, 8079, 5141, 6957],
 [7488, 1821, 1878, 6882, 7346, 7738, 9613, 2193],
 [1488, 6106, 1455, 9193, 9219, 9236, 9613, 1455, 4666, 1038, 6758, 6415],
 [4646, 1755, 4303, 2461, 9531, 6246, 4235, 6510],
 [9862, 9622, 5719, 2080, 9503],
 [990, 3264, 7904, 2859, 6544, 6611, 3416, 288, 7056, 6065, 9775, 5213],
 [901, 4930, 111, 9061, 2772, 5212, 4676, 9622, 9608, 84, 7653, 852],
 [8071, 8275, 9581, 9313, 8230],
 [112, 8136, 170, 4576, 4196, 9298, 9046],
 [8002, 3718, 7950, 6125, 3860, 8585, 1215, 3639, 7857, 9622],
 [3667, 7923],
 [9613, 4581, 7810, 1611],
 [7955, 8258, 1488, 2256, 1455, 328, 2391, 2903],
 [969, 4587, 4183, 2334, 1772, 3667, 2330, 2066, 4663],
 [3118, 631, 3377, 1234],
 [7543, 5480, 3335, 3765, 5290, 1994],
 [8739, 4659],
 [3241, 2983, 4389, 7955, 6166, 3763, 5846],
 [4315, 3985],
 [9965, 5339, 6390, 2170, 3424, 1542, 1437, 7658],
 [6978, 5971, 4593, 4424, 5040, 4663],
 [857, 9943, 8071, 4284, 3415, 2963, 1542, 1655],
 [8878, 3152, 5472, 4733, 3601, 2568],
 [9236, 4931, 3644, 4344, 757],
 [6773, 9521, 8829, 4112, 6029],
 [1401, 2895, 1873, 8617],
 [9807, 9466, 4389, 2921, 4297, 2799, 7011, 7778, 5040, 5099],
 [5379, 3518, 9991, 9581, 3530],
 [6068, 9864, 5370, 9527, 8927, 2303, 836, 3373, 7968, 8692],
 [4593, 6408, 1850, 7274, 4599, 4520, 2394],
 [7670, 2394, 6790, 5932, 5161, 7172, 1382, 1948, 2075, 1967],
 [3462, 9431, 901, 4930, 2772, 5212, 9775, 5213],
 [6453, 9046, 9896, 5108, 9186, 4697],
 [1455, 9193, 4448, 6224, 468, 9236, 4931, 9895, 8915],
 [9734, 6568, 4002, 8018, 8943, 3756, 5446, 4879, 5204],
 [6588, 3699, 3839, 2926, 4536, 2193, 9642, 3718],
 [9236, 4931, 4344, 1455, 9193, 5762, 4173],
 [8553, 4643, 1224, 2269],
 [6690, 1345, 9267, 5431, 3202, 8302, 9642, 2695, 3981, 1441, 1494],
 [8833, 8355, 2408, 7144, 1077, 1227, 3234],
 [6229, 517, 6224, 7050, 6909, 2878, 1433, 3359, 3056],
 [4930,
  8305,
  2277,
  3525,
  3511,
  1674,
  9613,
  5161,
  9188,
  6050,
  5208,
  5161,
  1410],
 [3394, 3170, 6983, 6908, 1224, 3046, 4893],
 [7653, 8973, 3044, 1755, 5061, 2763, 7301],
 [7723, 4477, 8027, 4877, 2080, 6653],
 [9854, 5719, 9173, 8545, 6358, 7520, 1410, 7301, 3860],
 [8146, 9907, 5040, 5753, 4137, 3218, 6224, 7113, 2303],
 [1927, 4930, 9188, 7670, 1264, 7679, 5002, 1419, 6611, 385, 1492],
 [94, 6882, 9631, 7645, 1507, 7172, 5597, 8670, 7239, 2973],
 [9050, 61, 2239, 8811, 1855, 5258, 5288],
 [7555, 4881, 5284, 1842, 9666, 2886, 6872, 7113],
 [4914, 8136, 1830, 3692, 9404, 5174, 8679, 5678, 2334, 7653],
 [1150,
  4697,
  7543,
  3290,
  1048,
  3290,
  1321,
  1048,
  4697,
  4525,
  5573,
  2922,
  4304,
  2819],
 [793,
  6690,
  1433,
  7607,
  4477,
  9613,
  5761,
  3416,
  5535,
  5775,
  1072,
  4284,
  8545,
  5151],
 [817, 8793, 4914],
 [9621,
  6531,
  5650,
  372,
  559,
  1656,
  711,
  2442,
  6931,
  7601,
  3969,
  9583,
  1224,
  2872,
  4409],
 [3359, 3056, 1043, 9945, 6229, 517, 2239, 8727, 5762, 495],
 [2926, 5988, 4002, 6660, 843, 7821, 2361, 1682, 5174, 8873],
 [1541, 3974, 1598, 4661, 2394, 8523, 3891, 3074],
 [5620, 9564, 4770, 3130, 2950, 6819, 2422, 6830, 7614, 9219, 2872],
 [8864, 798, 1492, 5762, 6464, 6106, 7016, 1826, 835, 2394, 1701, 4707],
 [6610, 1492, 3823, 9399, 2165, 3521, 8450, 8097],
 [1426, 5987, 5885],
 [868, 8560, 8149, 9770, 1626, 8195],
 [1195, 8279, 3130, 5499, 9678, 5678, 6394, 1488, 8887, 6100, 9389],
 [4950, 8295, 9273, 2316, 105, 798, 1454, 3335, 5473],
 [5656, 7588, 9497, 4388, 2075, 1432, 5713],
 [1455, 328, 2391, 2903, 3601, 2568],
 [2365, 1583],
 [7050, 2158, 1506, 3686, 791, 2698, 9661, 6106, 5967, 7328, 7613],
 [2334, 2193, 9056, 1662, 9613, 1215, 8774],
 [9779, 9193, 3644, 4389, 6106, 963, 8873, 4116],
 [563, 2394, 9621, 8385, 1958, 1230, 7287, 8224],
 [934, 2474, 5762, 5794, 3667, 341, 8692, 1463, 7833, 806, 3364],
 [6229, 517, 8831, 1071, 3359, 3056, 5174, 6947, 5121, 8873],
 [9273, 6573, 1094, 5384, 8240, 8751, 8572],
 [5213, 4930, 9945, 2947, 4239, 5290, 6635, 9136, 8572, 1242],
 [8482, 1753, 5488, 591, 1016, 3760, 2664, 8918],
 [736, 6252, 5337, 5575, 9399, 9142, 7171],
 [9883, 7328, 3860, 5280, 2422, 359, 5625],
 [8522, 1686, 2394, 1433, 5921, 5204, 7054],
 [8265, 3095, 7245, 4869, 9984, 8587, 8300, 1690],
 [3511, 1674, 7810, 8011, 1821, 111, 3583, 9676, 2494],
 [9056, 8217, 221, 5660, 4005, 7207, 8702, 9685],
 [7346, 3153, 8112, 1374, 4038, 1503, 9828, 3044, 2376, 3552, 6773],
 [8731, 5711, 9186, 5711, 2239, 4587, 8562],
 [9854, 7315, 6213, 9910, 3738, 459],
 [1594, 1242, 8255, 5081, 5318, 5126, 9273, 2828, 2066],
 [4225, 4116, 9726, 8882, 3728],
 [8731, 5711, 8340, 9093, 5711, 8880, 9119, 9613, 4277],
 [5213, 4930, 4389, 2334, 7955, 5439, 2285],
 [969, 4587, 3932, 2900, 5070, 1554, 3667, 2330, 3416, 962, 5161, 288],
 [9720, 6554, 3642, 6635, 8932, 3860, 6896, 1242, 45],
 [9697, 8944, 9572, 328, 2635, 4495, 6193, 2900, 6653],
 [3237, 9086, 7494, 2394, 5532, 4679, 5143],

In [ ]:
# embedding part

sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)
embedded_docs[0]

[[   0    0    0 ... 9768   92 6653]
 [   0    0    0 ... 8300 6872 2193]
 [   0    0    0 ... 2158 9824 7877]
 ...
 [   0    0    0 ... 3786  836 4096]
 [   0    0    0 ... 1372 1626 1261]
 [   0    0    0 ... 1947 1275 9046]]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 9076,
       3375, 1036, 6383, 9148, 3118,  631, 9768,   92, 6653], dtype=int32)

In [ ]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None

In [ ]:
## Creating model
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None

In [ ]:
len(embedded_docs),y.shape

(23196, (23196,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((23196, 20), (23196,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
### Finally Training
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
243/243 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - accuracy: 0.8589 - loss: 0.3325 - val_accuracy: 0.8265 - val_loss: 0.4071
Epoch 2/10
243/243 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.8829 - loss: 0.2828 - val_accuracy: 0.8192 - val_loss: 0.4152
Epoch 3/10
243/243 ━━━━━━━━━━━━━━━━━━━━ 16s 66ms/step - accuracy: 0.9001 - loss: 0.2458 - val_accuracy: 0.8063 - val_loss: 0.4433
Epoch 4/10
243/243 ━━━━━━━━━━━━━━━━━━━━ 17s 68ms/step - accuracy: 0.9214 - loss: 0.2047 - val_accuracy: 0.8060 - val_loss: 0.4999
Epoch 5/10
243/243 ━━━━━━━━━━━━━━━━━━━━ 17s 70ms/step - accuracy: 0.9358 - loss: 0.1725 - val_accuracy: 0.7901 - val_loss: 0.5415
Epoch 6/10
243/243 ━━━━━━━━━━━━━━━━━━━━ 19s 65ms/step - accuracy: 0.9469 - loss: 0.1460 - val_accuracy: 0.7974 - val_loss: 0.6068
Epoch 7/10
243/243 ━━━━━━━━━━━━━━━━━━━━ 16s 66ms/step - accuracy: 0.9552 - loss: 0.1257 - val_accuracy: 0.7858 - val_loss: 0.7109
Epoch 8/10
243/243 ━━━━━━━━━━━━━━━━━━━━ 17s 72ms/step - accuracy: 0.9610 - loss: 0.1117 - val_accuracy: 0.7872 - val_loss: 0.7281
Epoch 9/10
243/243 ━━━━━━━━━━━━━━━━━━━━ 17s 69ms/step - accuracy: 0.9665 - loss: 0.0939 - val_accuracy: 0.7903 - val_loss: 0.9086
Epoch 10/10
243/243 ━━━━━━━━━━━━━━━━━━━━ 16s 64ms/step - accuracy: 0.9690 - loss: 0.0877 - val_accuracy: 0.8022 - val_loss: 0.8622

In [ ]:
y_pred1=(model1.predict(X_test) > 0.5).astype("int32")

240/240 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred1)

array([[ 935,  919],
       [ 595, 5206]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred1)

0.8022207707380797

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.61      0.50      0.55      1854
           1       0.85      0.90      0.87      5801

    accuracy                           0.80      7655
   macro avg       0.73      0.70      0.71      7655
weighted avg       0.79      0.80      0.80      7655